---
name: Update Checker
env:
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Каждый день в 00:00 по UTC

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get Latest Commit Info
        id: getCommitInfo
        run: |
          COMMIT_INFO=$(curl -s "https://api.github.com/repos/openwrt/openwrt/branches/$REPO_BRANCH")
          COMMIT_HASH=$(echo $COMMIT_INFO | jq -r .commit.sha)
          COMMIT_DATE=$(echo $COMMIT_INFO | jq -r .commit.commit.committer.date)
          echo "::set-output name=commitHash::$COMMIT_HASH"
          echo "::set-output name=commitDate::$COMMIT_DATE"

      - name: Compare Commit Info
        id: compareCommit
        run: |
          if [ -f .lastCommitInfo ]; then
            LAST_HASH=$(cat .lastCommitInfo | head -n 1)
            LAST_DATE=$(cat .lastCommitInfo | tail -n 1)
            if [ "$LAST_HASH" != "${{ steps.getCommitInfo.outputs.commitHash }}" ] && [ "$LAST_DATE" != "${{ steps.getCommitInfo.outputs.commitDate }}" ]; then
              echo "Changes detected"
              echo "::set-output name=changed::true"
            else
              echo "No changes detected"
              echo "::set-output name=changed::false"
            fi
          else
            echo "First run, changes assumed"
            echo "::set-output name=changed::true"
          fi

      - name: Save New Commit Info
        if: steps.compareCommit.outputs.changed == 'true'
        run: |
          echo "${{ steps.getCommitInfo.outputs.commitHash }}" > .lastCommitInfo
          echo "${{ steps.getCommitInfo.outputs.commitDate }}" >> .lastCommitInfo

      - name: Trigger build
        if: steps.compareCommit.outputs.changed == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: Source Code Update

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
