# File: .github/workflows/update-checker.yml
---
# Inspired by P3TERX <https://p3terx.com>
#
# This file is part of Project Name and is released under the MIT License.
# See the LICENSE file for more details.
#
# Description: This workflow checks for updates in the OpenWrt repository and triggers a build if changes are detected.
#
# Key features:
# - Checks for updates in the OpenWrt repository
# - Triggers a build if changes are detected
# - Deletes old workflow runs to optimize disk space

name: Update Checker
env:
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  REPO_BRANCH: main

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get Latest Commit Info
        id: getCommitInfo
        run: |
          COMMIT_INFO=$(curl -s "https://api.github.com/repos/openwrt/openwrt/branches/$REPO_BRANCH")
          COMMIT_HASH=$(echo $COMMIT_INFO | jq -r .commit.sha)
          COMMIT_DATE=$(echo $COMMIT_INFO | jq -r .commit.commit.committer.date)
          echo "commitHash=$COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "commitDate=$COMMIT_DATE" >> $GITHUB_OUTPUT

      - name: Compare Commit Info
        id: compareCommit
        run: |
          if [ -f .lastCommitInfo ]; then
            LAST_HASH=$(cat .lastCommitInfo | head -n 1)
            LAST_DATE=$(cat .lastCommitInfo | tail -n 1)
            if [ "$LAST_HASH" != "${{ steps.getCommitInfo.outputs.commitHash }}" ] && [ "$LAST_DATE" != "${{ steps.getCommitInfo.outputs.commitDate }}" ]; then
              echo "Changes detected"
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              echo "No changes detected"
              echo "changed=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "First run, changes assumed"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Save New Commit Info
        if: steps.compareCommit.outputs.changed == 'true'
        run: |
          echo "${{ steps.getCommitInfo.outputs.commitHash }}" > .lastCommitInfo
          echo "${{ steps.getCommitInfo.outputs.commitDate }}" >> .lastCommitInfo

      - name: Trigger build
        if: steps.compareCommit.outputs.changed == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: Source Code Update

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
          delete_workflow_pattern: update-checker.yml
          delete_run_by_conclusion_pattern: success,failure,cancelled
